- name: gp
  configMap:
    name: gpsecserv
- name: data
  persistentVolumeClaim:
    claimName: data
- name: mdt
  persistentVolumeClaim:
    claimName: mdt
- name: dumps
  persistentVolumeClaim:
    claimName: hcdumps
- name: configmgt
  persistentVolumeClaim:
    claimName: configmgt